#!/bin/bash
set -e

echo "  [BashIt] postinst running..."

gtk-update-icon-cache -f -t /usr/share/icons/hicolor 2>/dev/null || true
gtk-update-icon-cache -f -t /usr/share/icons/lean-icons 2>/dev/null || true

echo "  [BashIt] install complete."
